### ISSUE TITLE
GSoC Completion

### ISSUE THREAD

**Issue by mronian** [JuliaImages/ImageFeatures.jl#13]
@timholy Google requires the students to submit a single link having the details of what work was done over the summer which will be displayed on their website and for their assessment. I was thinking of submitting something like this (its not yet done) - 

https://mronian.github.io/gsoc-2016/

I will put small details about the APIs etc under each heading. Is that good enough?

**Comment by timholy** [comment]
Looks very good. One possible point of confusion is that the relationship 
between "before the coding period" and the specific topics (starting with 
"exposure correction") could be a little confusing: was all that work done 
"before the coding period"? It might help to offset the "before" part from the 
"content" sections.

Also just to say, I'm really excited about your contributions! You have gotten 
me thinking about 3d keypoints and descriptors for our biomedical imaging 
registration application. Thanks for being my teacher as well as my student!

Best,
--Tim

**Comment by mronian** [comment]
Thanks for being an awesome mentor Tim!

**Comment by timholy** [comment]
Also, worth having a blog post about your work?

**Comment by mronian** [comment]
Of course! I would like to finish the documentation (doing it right now) before that so if anyone wants to try it out it will easy :)

**Comment by mronian** [comment]
@timholy I've tried to write the GSoC final submission page like a blog post :)

It can be viewed here - https://mronian.github.io/gsoc-2016/

Documentation is ready for the most part :smile:
