### ISSUE TITLE
Deploy docs with travis

### ISSUE THREAD

**Issue by mronian** [JuliaImages/ImageFeatures.jl#14]
I spent a lot of time trying to install the travis client on my system to sync the keys but there is some problem and I haven't been able to fix it. @timholy Incase you have it installed on your system, could you generate the travis key and .documenter.enc file ?

**Comment by mronian** [comment]
@rsrock I remember you had done the initial docs for TestImages.jl, if you could help deploy just an initial skeleton here it would be of great help :)

**Comment by mronian** [comment]
In case anyone has faced this before - 

On running `travis` I get this error - 

```
/usr/bin/env: ruby_executable_hooks1.9.1: No such file or directory
```

Googled it for a long time and tried many solutions but none seem to work.

**Comment by timholy** [comment]
I haven't seen that particular error. I did have trouble because I was trying to use my vendor-supplied `travis` command; things worked once I uninstalled it and built from source.

**Comment by timholy** [comment]
Is there a branch that already has `docs` defined, or should I start from scratch?

**Comment by timholy** [comment]
OK, should be ready now. (Reopen if further problems.)

**Comment by mronian** [comment]
I followed the documentation given here -> https://juliadocs.github.io/Documenter.jl/stable/man/hosting.html#Hosting-Documentation-1 but wasn't able to get travis to automatically push the docs to `gh-pages`. Anything else that needs to be done?

**Comment by timholy** [comment]
Check the Travis log; if you expand the triangle on the doc build step you'll see it's because `Distributions` got removed after testing finished, and that this caused an error. Check out https://github.com/JuliaImages/ImagesAxes.jl/blob/master/.travis.yml for one way to solve this problem.

**Comment by mronian** [comment]
Thanks a lot! Problem Solved :)

**Comment by timholy** [comment]
Notice it still says "skipping docs deployment," and unsurprisingly the docs link does not work for me.

**Comment by mronian** [comment]
You might have looked at the 'PR' builds. The docs are pushed only when I merge anything to the master branch. The link doesn't work because I had not pushed a home file to it. This works though -> http://juliaimages.github.io/ImageFeatures.jl/latest/function_reference/ :)

**Comment by timholy** [comment]
Oh, right. Carry on.

**Comment by mronian** [comment]
This is the master build -> https://travis-ci.org/JuliaImages/ImageFeatures.jl/jobs/153904356

**Comment by mronian** [comment]
A first draft of the docs is hosted here -> http://juliaimages.github.io/ImageFeatures.jl/latest/

@timholy I am unable to get the docstrings for Types to work. Function docstrings work correctly. Is there anything extra which has to be added for Types?

**Comment by mronian** [comment]
Problem solved after help from other GSoCers :)

**Comment by timholy** [comment]
Great, good to hear.
