### ISSUE TITLE
Histogram of oriented gradients implementation

### ISSUE THREAD

**Issue by hari-sikchi** [JuliaImages/ImageFeatures.jl#36]
I couldn't find the algorithm for Histogram of oriented gradients in the features module. @timholy  Is that feature required in this package and if so should I send a pull request for its implementation ?

**Comment by annimesh2809** [comment]
@hari-sikchi It seems like this algorithm is part of the [summer of code project](https://summerofcode.withgoogle.com/projects/#5707876516495360) of @tejus-gupta.

**Comment by hari-sikchi** [comment]
Oh, saw it just now. Thanks @annimesh2809

**Comment by hari-sikchi** [comment]
I am closing the issue then. @tejus-gupta

**Comment by timholy** [comment]
Thanks for checking first, @hari-sikchi! Excellent working-with-the-community skills :smile:.
