### ISSUE TITLE
Error while trying to run the HOG example

### ISSUE THREAD

**Issue by abhijithch** [JuliaImages/ImageFeatures.jl#47]
I am trying to run the example [here](https://github.com/JuliaImages/ImageFeatures.jl/blob/master/docs/src/tutorials/object_detection.md), after following the mentioned instructions. However I am running into the following error, 

```
ERROR: BoundsError: attempt to access 9×16×8 Array{Float64,3} at index [10, 1, 1]
Stacktrace:
 [1] trilinear_interpolate!(::Array{Float64,3}, ::Float64, ::Float64, ::Int64, ::CartesianIndex{2}, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64) at /Users/abhijith/.julia/v0.6/ImageFeatures/src/hog.jl:160
```

In the following iterator in hog.jl,
```
for i in R
        trilinear_interpolate!(hist, mag[i], phase[i], orientations, i, cell_size, Int(cell_rows), Int(cell_cols), rows, cols)
end
```
the error pops for `i=CartesianIndex{2}((6, 1))`. I tried with `Gray.(img)` too with the same problem.

**Comment by abhijithch** [comment]
The issue I think is this line `bin_θ1 = floor(Int, θ*orientations/180) + 1` when the `phase >= 180` the value `bin_θ1` is computed as 10, where as we have only 9 bins.

**Comment by simonbyrne** [comment]
This seems to have been fixed since the last release: can you tag a new one?

**Comment by simonbyrne** [comment]
Were you able to tag a new version?
