### ISSUE TITLE
coords_spatial not defined

### ISSUE THREAD

**Issue by feanor12** [JuliaImages/ImageFeatures.jl#93]
I think this might be caused by the renaming planned
 https://github.com/JuliaImages/Images.jl/issues/767

 [92ff4b2b] ImageFeatures v0.4.5
 [916415d5] Images v0.24.1

Works in Images v0.24.0

```
UndefVarError: coords_spatial not defined

findlocalmaxima(::Matrix{Int64})@algorithms.jl:427
var"#hough_circle_gradient#77"(::Int64, ::Int64, ::Int64, ::typeof(ImageFeatures.hough_circle_gradient), ::Matrix{Bool}, ::Matrix{Float64}, ::UnitRange{Int64})@houghtransform.jl:204
hough_circle_gradient(::Matrix{Bool}, ::Matrix{Float64}, ::UnitRange{Int64})@houghtransform.jl:163
(::Main.workspace65.var"#1#2")(::String)@Local: 8
iterate@generator.jl:47[inlined]
_collect(::Vector{String}, ::Base.Generator{Vector{String}, Main.workspace65.var"#1#2"}, ::Base.EltypeUnknown, ::Base.HasShape{1})@array.jl:691
collect_similar(::Vector{String}, ::Base.Generator{Vector{String}, Main.workspace65.var"#1#2"})@array.jl:606
map(::Function, ::Vector{String})@abstractarray.jl:2294
top-level scope@Local: 3
```

**Comment by johnnychen94** [comment]
`coords_spatial` has [not changed for years](https://github.com/JuliaImages/ImageCore.jl/blob/4fb132187d68054be7413ec229071115c14f72bd/src/traits.jl#L110-L128), and there are no related changes during Images 0.24.0 and 0.24.1, perhaps it's other issue that triggers this error. Could you provide a minimal working example that I can run and check?

**Comment by feanor12** [comment]
Thanks for the fast feedback.
I tried on a new environment and it seems to work with 0.24.1.
I'll try to see if I can find the root cause in my other setup.

**Comment by feanor12** [comment]
I updated the failing project again and I cant reproduce the error anymore.
